apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rabbitmq-cluster
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rabbitmq-cluster
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim3
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rabbitmq-cluster
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim4
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rabbitmq-cluster
  resources:
    requests:
      storage: 1Gi
